#!/bin/sh

set -eu

endpoint="${RUSTFS_ENDPOINT:-http://rustfs:9000}"
bucket="${UC_STORAGE_BUCKET:-uc-warehouse}"
region="${S3_REGION:-us-east-1}"
duration="${STS_DURATION_SECONDS:-43200}"
uc_auth="${UC_AUTH:-disable}"
postgres_host="${POSTGRES_HOST:-postgres}"
postgres_db="${POSTGRES_DB:-ucdb}"
postgres_user="${POSTGRES_USER:-uc_default_user}"
postgres_password="${POSTGRES_PASSWORD:-uc_default_password}"

export AWS_ACCESS_KEY_ID="${RUSTFS_ACCESS_KEY:-rustfsadmin}"
export AWS_SECRET_ACCESS_KEY="${RUSTFS_SECRET_KEY:-rustfsadmin}"
export AWS_DEFAULT_REGION="$region"

log() {
  echo "[rustfs-init] $*"
}

log "waiting for RustFS at $endpoint"
attempt=0
until aws --endpoint-url "$endpoint" s3api list-buckets >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ "$attempt" -ge 60 ]; then
    log "RustFS did not become ready in time" >&2
    exit 1
  fi
  sleep 2
done

if ! aws --endpoint-url "$endpoint" s3api head-bucket --bucket "$bucket" >/dev/null 2>&1; then
  log "creating s3://$bucket"
  aws --endpoint-url "$endpoint" s3api create-bucket --bucket "$bucket" >/dev/null
fi

log "minting RustFS STS credentials"
credentials="$(aws --endpoint-url "$endpoint" sts assume-role \
  --role-arn "arn:aws:iam::000000000000:role/unity-catalog" \
  --role-session-name "unity-catalog-bootstrap" \
  --duration-seconds "$duration" \
  --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
  --output text)"

access_key="$(printf '%s\n' "$credentials" | awk '{print $1}')"
secret_key="$(printf '%s\n' "$credentials" | awk '{print $2}')"
session_token="$(printf '%s\n' "$credentials" | awk '{print $3}')"

if [ -z "$access_key" ] || [ -z "$secret_key" ] || [ -z "$session_token" ]; then
  log "RustFS did not return complete STS credentials" >&2
  exit 1
fi

mkdir -p /conf
for template in /templates/*.properties; do
  name="$(basename "$template")"
  cp -f "$template" "/conf/$name"
done

{
  printf '\n# Local Compose overrides generated by rustfs-init.\n'
  printf 'server.authorization=%s\n' "$uc_auth"
  printf 'server.managed-table.enabled=true\n'
  printf 'server.managed-table.use-delta-api-only=true\n'
  printf 'storage-root.tables=s3://%s\n' "$bucket"
  printf 's3.bucketPath.0=s3://%s\n' "$bucket"
  printf 's3.region.0=%s\n' "$region"
  printf 's3.secretKey.0=%s\n' "$secret_key"
  printf 's3.accessKey.0=%s\n' "$access_key"
  printf 's3.sessionToken.0=%s\n' "$session_token"
} >> /conf/server.properties

{
  printf '\n# Local Compose overrides generated by rustfs-init.\n'
  printf 'hibernate.connection.driver_class=org.postgresql.Driver\n'
  printf 'hibernate.connection.url=jdbc:postgresql://%s:5432/%s\n' "$postgres_host" "$postgres_db"
  printf 'hibernate.connection.username=%s\n' "$postgres_user"
  printf 'hibernate.connection.password=%s\n' "$postgres_password"
} >> /conf/hibernate.properties

log "configured Unity Catalog for s3://$bucket with authorization=$uc_auth"
